### PR TITLE
refactor: replace crypto dependencies

### PR DESCRIPTION
**Pull request by janniks**
## scope
- npm audit fix
- remove elliptic, sha.js for smaller/no-polyfill [@noble/hashes](https://github.com/paulmillr/noble-hashes) [@noble/secp256k1](https://github.com/paulmillr/noble-secp256k1)
- refactor some conditions for less nesting/complexity, push down negations
- update dev dependencies
  - update lint ruleset to match current code (unless minor change fixes problem)
  - fix minor prettier/eslint problems
  - re-format all files to match latest config files

## bundle size comparison
📦 **decrease of 55%**

Screen Shot 2022-05-10 at 18 20

### CODE REVIEW

**Comment by janniks** [comment]
@kantai @zone117x please review (especially crypto functions marked by comments). the options i provided fit the test suite, but i'm not familiar enough with them to tell if everything is correct/intended.

i also added some ci workflows to auto-publish pull request beta versions and publish on merge — but somebody likely has to allow these, add me to the repo, add the NPM_TOKEN as a secret, etc; CC: @CharlieC3

**Review by kantai — APPROVED** [review]
This all looks good to me, @janniks, thanks!

**Comment by CharlieC3** [comment]
@janniks Some of our other repos already have an [established method](https://github.com/hirosystems/gh-actions-example#configure-a-repo-with-automatic-semantic-versioning) of publishing NPM packages and beta releases automatically. I wonder if it would be easier to implement and maintain that in this project?
If so, I can help implement it if you create a devops ticket. Additionally, we could exclude the GH workflow changes in this PR so it's not a blocker and create a separate branch/PR to implement it.

What are your thoughts?

**Comment by janniks** [comment]
@CharlieC3 yeah, i cloned the workflows from @stacks/connect and modified to be as minimal as possible and not use lerna, semantic release, etc. since this repo was pretty manually handled before and i don't anticipate many changes to the repo/package...

i'll check if it's trivial to move to the established flow

**Comment by CharlieC3** [comment]
@janniks Either way is fine with me! Wasn't sure if you were aware of the semantic-release method we were using elsewhere, and wanted to offer a possible alternative. If what you committed is easier to manage going forward, that's fine too.

**Review by zone117x — APPROVED** [review]
LGTM!
We should kill the `buffer` polyfill lib next.

**Comment by janniks** [comment]
@zone117x yes, removed it here — doesn't make sense to add if we need to remove in a couple of weeks...
folks can still easily globally polyfill it manually (without config changes) while stacks.js uses `buffer/`

**Comment by janniks** [comment]
> @zone117x yes, removed it here

Added `buffer` again, looks like webpack was previously polyfilling it 🙃 (will be removed soon-ish, when stacks.js + jsontokens major bumps to Uint8Arrays)

**Comment by janniks** [comment]
CC @CharlieC3 could you merge this one as well? same `ci/circleci required` issue

**Comment by CharlieC3** [comment]
@janniks Done!

**Pull request merged**
